[package]
name = "devprofiler"
version = "0.2.3"
edition = "2021"
sha256 = "1.1.1"
walkdir = "2"
inquire = "0.5.2"
pkg-config = "0.3.26"
reqwest = { version = "0.11", features = ["blocking", "json"] }

# todo - check all lib licences
